[build.environment]
  # Logo
    NEXT_PUBLIC_LOGO_PATH="/logo.png"

    # Home page

    NEXT_PUBLIC_URL="http://localhost:3000/"
    NEXT_PUBLIC_TOKEN_NAME="Benefits Airdrop"
    NEXT_PUBLIC_HEADING="Juicebox DAO Benefits Airdrop"
    NEXT_PUBLIC_DESCRIPTION="Claim your JBX airdrop today. Allocations are calculated based on your Juicebox DAO Benefits Score — powered by ARCx."
    NEXT_PUBLIC_COLOUR_PRIMARY="EAB75F"
    NEXT_PUBLIC_COLOUR_SECONDARY="B08A49"

    # Social links
    NEXT_PUBLIC_DISCORD="https://discord.gg/6jXrJSyDFf"
    NEXT_PUBLIC_TWITTER="https://twitter.com/juiceboxETH"
    NEXT_PUBLIC_ARTICLE="https://mirror.xyz/"
    NEXT_PUBLIC_GITHUB="https://github.com/jbx-protocol/"

    # Functionality
    NEXT_PUBLIC_CONTRACT_ADDRESS="0x518e3CdBcda4f0735399c9F1e03A7aBC7562632f"
    NEXT_PUBLIC_RPC_NETWORK="1"